#!/bin/bash

# Script to tune Linux kernel parameters for DDS buffer issues
# Based on ROS 2 DDS tuning recommendations for Fast RTPS
#
# This addresses issues with:
# - IP fragment buffer overflow on lossy (WiFi) connections
# - Large message delivery problems
# - Network flooding with fast-published data

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="/etc/sysctl.d"

echo "=========================================="
echo "DDS Buffer Tuning Script"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "Error: This script must be run as root (use sudo)"
    exit 1
fi

echo "Applying kernel parameter tunings for DDS buffer issues..."
echo ""

# 1. Reduce IP fragment timeout (default: 30s -> 3s)
# This reduces the window where fragments can block the buffer
echo "1. Reducing IP fragment timeout (ipfrag_time: 30s -> 3s)..."
sysctl -w net.ipv4.ipfrag_time=3
echo "   ✓ Set net.ipv4.ipfrag_time=3"

# 2. Increase IP fragment buffer size (default: 256KB -> 128MB)
# This prevents the buffer from becoming completely full
echo "2. Increasing IP fragment buffer size (ipfrag_high_thresh: 256KB -> 128MB)..."
sysctl -w net.ipv4.ipfrag_high_thresh=134217728  # 128 MB in bytes
echo "   ✓ Set net.ipv4.ipfrag_high_thresh=134217728 (128MB)"

# 3. Increase maximum receive buffer size (for large messages)
# This is important for Fast RTPS and other DDS implementations
echo "3. Increasing maximum receive buffer size (rmem_max)..."
sysctl -w net.core.rmem_max=2147483647  # 2GB (maximum)
echo "   ✓ Set net.core.rmem_max=2147483647 (2GB)"

# 4. Also increase default receive buffer sizes
echo "4. Increasing default receive buffer sizes..."
sysctl -w net.core.rmem_default=8388608  # 8MB default
echo "   ✓ Set net.core.rmem_default=8388608 (8MB)"

# Make changes persistent
echo ""
echo "Making changes persistent..."
CONFIG_FILE="${CONFIG_DIR}/99-dds-buffer-tuning.conf"
cat > "${CONFIG_FILE}" << EOF
# DDS Buffer Tuning Configuration
# Generated by tune_dds_buffers.sh
# 
# These settings address buffer overflow issues with DDS implementations
# (Fast RTPS, Cyclone DDS, RTI Connext) on Linux systems

# IP Fragment Management
# Reduce timeout to prevent long blocking periods when fragments are lost
net.ipv4.ipfrag_time = 3

# Increase buffer size to prevent overflow on lossy connections (WiFi)
net.ipv4.ipfrag_high_thresh = 134217728

# Socket Receive Buffer Sizes
# Increase maximum receive buffer for large message delivery
net.core.rmem_max = 2147483647

# Increase default receive buffer size
net.core.rmem_default = 8388608
EOF

echo "   ✓ Created persistent configuration: ${CONFIG_FILE}"
echo ""

echo "=========================================="
echo "Current Settings:"
echo "=========================================="
echo "net.ipv4.ipfrag_time: $(sysctl -n net.ipv4.ipfrag_time)s"
echo "net.ipv4.ipfrag_high_thresh: $(sysctl -n net.ipv4.ipfrag_high_thresh) bytes ($(($(sysctl -n net.ipv4.ipfrag_high_thresh) / 1024 / 1024))MB)"
echo "net.core.rmem_max: $(sysctl -n net.core.rmem_max) bytes ($(($(sysctl -n net.core.rmem_max) / 1024 / 1024))MB)"
echo "net.core.rmem_default: $(sysctl -n net.core.rmem_default) bytes ($(($(sysctl -n net.core.rmem_default) / 1024 / 1024))MB)"
echo ""

echo "=========================================="
echo "Tuning Complete!"
echo "=========================================="
echo ""
echo "Note: These settings will persist across reboots."
echo "To revert, delete: ${CONFIG_FILE}"
echo ""

